"""initial schema

Revision ID: 22fde5ee3e4b
Revises: 
Create Date: 2026-07-20 00:55:52.643069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22fde5ee3e4b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama')
    )
    op.create_index(op.f('ix_kategori_id'), 'kategori', ['id'], unique=False)
    op.create_table('pelanggan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=150), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('telepon', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pelanggan_id'), 'pelanggan', ['id'], unique=False)
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=150), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('telepon', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_id'), 'supplier', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('barang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode', sa.String(length=30), nullable=False),
    sa.Column('nama', sa.String(length=200), nullable=False),
    sa.Column('kategori_id', sa.Integer(), nullable=True),
    sa.Column('harga_beli', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('harga_jual', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('stok', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kategori_id'], ['kategori.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode')
    )
    op.create_index(op.f('ix_barang_id'), 'barang', ['id'], unique=False)
    op.create_table('pembelian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no_faktur', sa.String(length=30), nullable=False),
    sa.Column('tanggal', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('total', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('no_faktur')
    )
    op.create_index(op.f('ix_pembelian_id'), 'pembelian', ['id'], unique=False)
    op.create_table('penjualan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no_faktur', sa.String(length=30), nullable=False),
    sa.Column('tanggal', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('pelanggan_id', sa.Integer(), nullable=True),
    sa.Column('total', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('diskon', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('grand_total', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pelanggan_id'], ['pelanggan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('no_faktur')
    )
    op.create_index(op.f('ix_penjualan_id'), 'penjualan', ['id'], unique=False)
    op.create_table('detail_pembelian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pembelian_id', sa.Integer(), nullable=False),
    sa.Column('barang_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('harga_beli', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('subtotal', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['barang_id'], ['barang.id'], ),
    sa.ForeignKeyConstraint(['pembelian_id'], ['pembelian.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detail_pembelian_id'), 'detail_pembelian', ['id'], unique=False)
    op.create_table('detail_penjualan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('penjualan_id', sa.Integer(), nullable=True),
    sa.Column('barang_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('harga_jual', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('subtotal', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['barang_id'], ['barang.id'], ),
    sa.ForeignKeyConstraint(['penjualan_id'], ['penjualan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detail_penjualan_id'), 'detail_penjualan', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detail_penjualan_id'), table_name='detail_penjualan')
    op.drop_table('detail_penjualan')
    op.drop_index(op.f('ix_detail_pembelian_id'), table_name='detail_pembelian')
    op.drop_table('detail_pembelian')
    op.drop_index(op.f('ix_penjualan_id'), table_name='penjualan')
    op.drop_table('penjualan')
    op.drop_index(op.f('ix_pembelian_id'), table_name='pembelian')
    op.drop_table('pembelian')
    op.drop_index(op.f('ix_barang_id'), table_name='barang')
    op.drop_table('barang')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_supplier_id'), table_name='supplier')
    op.drop_table('supplier')
    op.drop_index(op.f('ix_pelanggan_id'), table_name='pelanggan')
    op.drop_table('pelanggan')
    op.drop_index(op.f('ix_kategori_id'), table_name='kategori')
    op.drop_table('kategori')
    # ### end Alembic commands ###
