"""add purchase relationships

Revision ID: 7cfb0587f4f9
Revises: b426e3195ec8
Create Date: 2026-07-20 04:00:58.290592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7cfb0587f4f9'
down_revision: Union[str, Sequence[str], None] = 'b426e3195ec8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_detail_pembelian_id'), 'detail_pembelian', ['id'], unique=False)
    op.alter_column('pembelian', 'keterangan',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pembelian', 'keterangan',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_detail_pembelian_id'), table_name='detail_pembelian')
    # ### end Alembic commands ###
