"""add supplier table

Revision ID: b426e3195ec8
Revises: 22fde5ee3e4b
Create Date: 2026-07-20 02:44:27.342089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b426e3195ec8'
down_revision: Union[str, Sequence[str], None] = '22fde5ee3e4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barang', sa.Column('kode_barang', sa.String(length=30), nullable=False))
    op.add_column('barang', sa.Column('nama_barang', sa.String(length=200), nullable=False))
    op.add_column('barang', sa.Column('satuan', sa.String(length=20), nullable=True))
    op.add_column('barang', sa.Column('stok_minimum', sa.Integer(), nullable=True))
    op.drop_index(op.f('kode'), table_name='barang')
    op.create_unique_constraint(None, 'barang', ['kode_barang'])
    op.drop_column('barang', 'nama')
    op.drop_column('barang', 'kode')
    op.add_column('supplier', sa.Column('kode_supplier', sa.String(length=20), nullable=False))
    op.add_column('supplier', sa.Column('kontak', sa.String(length=100), nullable=True))
    op.add_column('supplier', sa.Column('kota', sa.String(length=100), nullable=True))
    op.add_column('supplier', sa.Column('provinsi', sa.String(length=100), nullable=True))
    op.add_column('supplier', sa.Column('kode_pos', sa.String(length=10), nullable=True))
    op.add_column('supplier', sa.Column('catatan', sa.Text(), nullable=True))
    op.add_column('supplier', sa.Column('aktif', sa.Boolean(), nullable=True))
    op.add_column('supplier', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('supplier', 'nama',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('supplier', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.create_unique_constraint(None, 'supplier', ['kode_supplier'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supplier', type_='unique')
    op.alter_column('supplier', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('supplier', 'nama',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)
    op.drop_column('supplier', 'updated_at')
    op.drop_column('supplier', 'aktif')
    op.drop_column('supplier', 'catatan')
    op.drop_column('supplier', 'kode_pos')
    op.drop_column('supplier', 'provinsi')
    op.drop_column('supplier', 'kota')
    op.drop_column('supplier', 'kontak')
    op.drop_column('supplier', 'kode_supplier')
    op.add_column('barang', sa.Column('kode', mysql.VARCHAR(length=30), nullable=False))
    op.add_column('barang', sa.Column('nama', mysql.VARCHAR(length=200), nullable=False))
    op.drop_constraint(None, 'barang', type_='unique')
    op.create_index(op.f('kode'), 'barang', ['kode'], unique=True)
    op.drop_column('barang', 'stok_minimum')
    op.drop_column('barang', 'satuan')
    op.drop_column('barang', 'nama_barang')
    op.drop_column('barang', 'kode_barang')
    # ### end Alembic commands ###
